add_test( [==[Time system - basic step]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - basic step]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - basic step]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Time system - zero delta time]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - zero delta time]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - zero delta time]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Time system - half tick accumulation]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - half tick accumulation]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - half tick accumulation]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Time system - negative delta time clamping]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - negative delta time clamping]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - negative delta time clamping]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Time system - max step clamping]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - max step clamping]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - max step clamping]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Time system - alpha with zero tick_dt]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Time system - alpha with zero tick_dt]==] [==[--order rand]==]  )
set_tests_properties( [==[Time system - alpha with zero tick_dt]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - deterministic sequence]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - deterministic sequence]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - deterministic sequence]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - int range bounds]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - int range bounds]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - int range bounds]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - seed zero sets default state]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - seed zero sets default state]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - seed zero sets default state]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - float 0-1 range]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - float 0-1 range]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - float 0-1 range]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - float range bounds]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - float range bounds]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - float range bounds]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[RNG - inverted int range returns min]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[RNG - inverted int range returns min]==] [==[--order rand]==]  )
set_tests_properties( [==[RNG - inverted int range returns min]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Engine - initialization and time update]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Engine - initialization and time update]==] [==[--order rand]==]  )
set_tests_properties( [==[Engine - initialization and time update]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Engine - alpha value range]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Engine - alpha value range]==] [==[--order rand]==]  )
set_tests_properties( [==[Engine - alpha value range]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Game constants - GPU entity count]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Game constants - GPU entity count]==] [==[--order rand]==]  )
set_tests_properties( [==[Game constants - GPU entity count]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Visual Test (Headless Game Run)]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Visual Test (Headless Game Run)]==] [==[--order rand]==]  )
set_tests_properties( [==[Visual Test (Headless Game Run)]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[GameRender - World creation WITHOUT window]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[GameRender - World creation WITHOUT window]==] [==[--order rand]==]  )
set_tests_properties( [==[GameRender - World creation WITHOUT window]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[GameRender - Rendering with window (shader loads lazily)]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[GameRender - Rendering with window (shader loads lazily)]==] [==[--order rand]==]  )
set_tests_properties( [==[GameRender - Rendering with window (shader loads lazily)]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Rendering Debug - Check microbe rendering setup]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Rendering Debug - Check microbe rendering setup]==] [==[--order rand]==]  )
set_tests_properties( [==[Rendering Debug - Check microbe rendering setup]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeSpawn - Microbes accumulate without being destroyed]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeSpawn - Microbes accumulate without being destroyed]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeSpawn - Microbes accumulate without being destroyed]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeSpawn - Entity count increases correctly]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeSpawn - Entity count increases correctly]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeSpawn - Entity count increases correctly]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeSpawn - Check for physics body accumulation]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeSpawn - Check for physics body accumulation]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeSpawn - Check for physics body accumulation]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Game - Initial microbes persist during spawn]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Game - Initial microbes persist during spawn]==] [==[--order rand]==]  )
set_tests_properties( [==[Game - Initial microbes persist during spawn]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SpawnSystem - Microbes spawn at different positions]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SpawnSystem - Microbes spawn at different positions]==] [==[--order rand]==]  )
set_tests_properties( [==[SpawnSystem - Microbes spawn at different positions]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Microbe spawning - Verify existing microbes keep their positions]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Microbe spawning - Verify existing microbes keep their positions]==] [==[--order rand]==]  )
set_tests_properties( [==[Microbe spawning - Verify existing microbes keep their positions]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - subdivision 0 (base icosahedron)]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - subdivision 0 (base icosahedron)]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - subdivision 0 (base icosahedron)]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - subdivision 1]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - subdivision 1]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - subdivision 1]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - subdivision 2]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - subdivision 2]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - subdivision 2]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - custom radius]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - custom radius]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - custom radius]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - edge generation subdivision 0]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - edge generation subdivision 0]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - edge generation subdivision 0]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Icosphere - edge generation subdivision 1]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Icosphere - edge generation subdivision 1]==] [==[--order rand]==]  )
set_tests_properties( [==[Icosphere - edge generation subdivision 1]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - edge generation subdivision 0]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - edge generation subdivision 0]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - edge generation subdivision 0]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - edge generation subdivision 1]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - edge generation subdivision 1]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - edge generation subdivision 1]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - rigid sphere preset]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - rigid sphere preset]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - rigid sphere preset]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - jelly sphere preset]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - jelly sphere preset]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - jelly sphere preset]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - volume constraint compliance]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - volume constraint compliance]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - volume constraint compliance]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - volume constraint mesh size invariance]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - volume constraint mesh size invariance]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - volume constraint mesh size invariance]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[Constraints - edge uniqueness (no duplicates)]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[Constraints - edge uniqueness (no duplicates)]==] [==[--order rand]==]  )
set_tests_properties( [==[Constraints - edge uniqueness (no duplicates)]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Create amoeba soft body]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Create amoeba soft body]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Create amoeba soft body]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Verify vertex count]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Verify vertex count]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Verify vertex count]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Extract vertex positions]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Extract vertex positions]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Extract vertex positions]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Soft body properties]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Soft body properties]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Soft body properties]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Invalid body ID handling]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Invalid body ID handling]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Invalid body ID handling]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[SoftBodyFactory - Simulation step]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[SoftBodyFactory - Simulation step]==] [==[--order rand]==]  )
set_tests_properties( [==[SoftBodyFactory - Simulation step]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Initialize locomotion state]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Initialize locomotion state]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Initialize locomotion state]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Phase progression]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Phase progression]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Phase progression]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Phase transitions]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Phase transitions]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Phase transitions]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Extension forces modify vertex velocity]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Extension forces modify vertex velocity]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Extension forces modify vertex velocity]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Wiggle phase updates]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Wiggle phase updates]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Wiggle phase updates]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Target vertex selection on cycle reset]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Target vertex selection on cycle reset]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Target vertex selection on cycle reset]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[ECMLocomotion - Retraction forces pull body toward anchored foot (Body Pull)]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[ECMLocomotion - Retraction forces pull body toward anchored foot (Body Pull)]==] [==[--order rand]==]  )
set_tests_properties( [==[ECMLocomotion - Retraction forces pull body toward anchored foot (Body Pull)]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Create amoeba entity]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Create amoeba entity]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Create amoeba entity]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Microbe simulation updates]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Microbe simulation updates]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Microbe simulation updates]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Multiple amoebas interact]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Multiple amoebas interact]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Multiple amoebas interact]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Transform sync from physics]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Transform sync from physics]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Transform sync from physics]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Vertex extraction during simulation]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Vertex extraction during simulation]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Vertex extraction during simulation]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Locomotion affects soft body]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Locomotion affects soft body]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Locomotion affects soft body]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
add_test( [==[MicrobeIntegration - Stress test - 10 amoebas]==] /home/dgpt/code/games/micro-idle/build_native/tests [==[MicrobeIntegration - Stress test - 10 amoebas]==] [==[--order rand]==]  )
set_tests_properties( [==[MicrobeIntegration - Stress test - 10 amoebas]==] PROPERTIES WORKING_DIRECTORY /home/dgpt/code/games/micro-idle/build_native TIMEOUT 2)
set( tests_TESTS [==[Time system - basic step]==] [==[Time system - zero delta time]==] [==[Time system - half tick accumulation]==] [==[Time system - negative delta time clamping]==] [==[Time system - max step clamping]==] [==[Time system - alpha with zero tick_dt]==] [==[RNG - deterministic sequence]==] [==[RNG - int range bounds]==] [==[RNG - seed zero sets default state]==] [==[RNG - float 0-1 range]==] [==[RNG - float range bounds]==] [==[RNG - inverted int range returns min]==] [==[Engine - initialization and time update]==] [==[Engine - alpha value range]==] [==[Game constants - GPU entity count]==] [==[Visual Test (Headless Game Run)]==] [==[GameRender - World creation WITHOUT window]==] [==[GameRender - Rendering with window (shader loads lazily)]==] [==[Rendering Debug - Check microbe rendering setup]==] [==[MicrobeSpawn - Microbes accumulate without being destroyed]==] [==[MicrobeSpawn - Entity count increases correctly]==] [==[MicrobeSpawn - Check for physics body accumulation]==] [==[Game - Initial microbes persist during spawn]==] [==[SpawnSystem - Microbes spawn at different positions]==] [==[Microbe spawning - Verify existing microbes keep their positions]==] [==[Icosphere - subdivision 0 (base icosahedron)]==] [==[Icosphere - subdivision 1]==] [==[Icosphere - subdivision 2]==] [==[Icosphere - custom radius]==] [==[Icosphere - edge generation subdivision 0]==] [==[Icosphere - edge generation subdivision 1]==] [==[Constraints - edge generation subdivision 0]==] [==[Constraints - edge generation subdivision 1]==] [==[Constraints - rigid sphere preset]==] [==[Constraints - jelly sphere preset]==] [==[Constraints - volume constraint compliance]==] [==[Constraints - volume constraint mesh size invariance]==] [==[Constraints - edge uniqueness (no duplicates)]==] [==[SoftBodyFactory - Create amoeba soft body]==] [==[SoftBodyFactory - Verify vertex count]==] [==[SoftBodyFactory - Extract vertex positions]==] [==[SoftBodyFactory - Soft body properties]==] [==[SoftBodyFactory - Invalid body ID handling]==] [==[SoftBodyFactory - Simulation step]==] [==[ECMLocomotion - Initialize locomotion state]==] [==[ECMLocomotion - Phase progression]==] [==[ECMLocomotion - Phase transitions]==] [==[ECMLocomotion - Extension forces modify vertex velocity]==] [==[ECMLocomotion - Wiggle phase updates]==] [==[ECMLocomotion - Target vertex selection on cycle reset]==] [==[ECMLocomotion - Retraction forces pull body toward anchored foot (Body Pull)]==] [==[MicrobeIntegration - Create amoeba entity]==] [==[MicrobeIntegration - Microbe simulation updates]==] [==[MicrobeIntegration - Multiple amoebas interact]==] [==[MicrobeIntegration - Transform sync from physics]==] [==[MicrobeIntegration - Vertex extraction during simulation]==] [==[MicrobeIntegration - Locomotion affects soft body]==] [==[MicrobeIntegration - Stress test - 10 amoebas]==])
